/**
 * Major PU locations for the tactical map UI (Stanton, Pyro, Nyx).
 * Names follow in-game / Galactapedia / starcitizen.tools where available; schematic orbit angles are for display only.
 */

export const POI_KIND = {
  city: { label: 'City / LZ', color: '#e5c07b' },
  station: { label: 'Station', color: '#7aa2f7' },
  outpost: { label: 'Outpost', color: '#9ece6a' },
  landing: { label: 'Landing / shelter', color: '#9ece6a' },
  mining: { label: 'Mining / HDMS', color: '#bb9af7' },
  comm_array: { label: 'Comm array', color: '#f7768e' },
  gate: { label: 'Jump gate', color: '#7dcfff' },
  lagrange: { label: 'Lagrange / platform', color: '#565f89' },
  racetrack: { label: 'Racetrack', color: '#ff9e64' },
  industrial: { label: 'Industrial', color: '#c0a36e' },
  orbital: { label: 'Orbital marker', color: '#89ddff' },
  asteroid_belt: { label: 'Asteroid belt', color: '#a9b1d6' },
}

/** Orbit diagram + POI inventory for Stanton (PU). */
export const STANTON_BODIES = [
  {
    name: 'Hurston',
    orbit: 0.2,
    angle: 25,
    color: '#8B5E3C',
    r: 2.5,
    pois: [
      { name: 'Lorville', kind: 'city' },
      { name: 'Everus Harbor', kind: 'station' },
      { name: 'Comm Array ST1-61', kind: 'comm_array' },
      { name: 'Reclamation & Disposal East', kind: 'industrial' },
      { name: 'Reclamation & Disposal West', kind: 'industrial' },
    ],
    moons: [
      {
        name: 'Aberdeen',
        pois: [
          { name: 'Klescher Rehabilitation Facility', kind: 'station' },
          { name: 'HDMS-Norgaard', kind: 'mining' },
          { name: 'HDMS-Anderson', kind: 'mining' },
          { name: 'Comm Array ST1-92', kind: 'comm_array' },
        ],
      },
      {
        name: 'Arial',
        pois: [
          { name: 'HDMS-Bezdek', kind: 'mining' },
          { name: 'HDMS-Lathan', kind: 'mining' },
          { name: 'Coven', kind: 'outpost' },
          { name: 'Smokestack', kind: 'outpost' },
          { name: 'The Dregs', kind: 'outpost' },
          { name: 'Comm Array ST1-13', kind: 'comm_array' },
        ],
      },
      {
        name: 'Ita',
        pois: [
          { name: 'HDMS-Ryder', kind: 'mining' },
          { name: 'HDMS-Woodruff', kind: 'mining' },
          { name: 'The Shades', kind: 'outpost' },
          { name: 'Thimblerig', kind: 'outpost' },
          { name: 'Comm Array ST1-02', kind: 'comm_array' },
        ],
      },
      {
        name: 'Magda',
        pois: [
          { name: 'HDMS-Hahn', kind: 'mining' },
          { name: 'HDMS-Perlman', kind: 'mining' },
          { name: 'Gonzo', kind: 'outpost' },
          { name: 'Nevermind', kind: 'outpost' },
          { name: 'Comm Array ST1-48', kind: 'comm_array' },
        ],
      },
    ],
  },
  {
    name: 'Crusader',
    orbit: 0.38,
    angle: 145,
    color: '#4a7fa5',
    r: 3.5,
    pois: [
      { name: 'Orison', kind: 'city' },
      { name: 'Seraphim Station', kind: 'station' },
      { name: 'Comm Array ST2-55', kind: 'comm_array' },
      { name: 'Crusader shipyard platforms', kind: 'industrial' },
    ],
    moons: [
      {
        name: 'Daymar',
        pois: [
          { name: 'ArcCorp Mining Area 141', kind: 'mining' },
          { name: 'Shubin Mining Facility SCD-1', kind: 'mining' },
          { name: 'Bountiful Harvest Hydroponics', kind: 'outpost' },
          { name: "Brio's Breaker Yard", kind: 'industrial' },
          { name: 'Jumptown', kind: 'industrial' },
          { name: 'Security Post Moluto', kind: 'outpost' },
          { name: 'Security Post Thaquray', kind: 'outpost' },
          { name: 'Security Post Prashad', kind: 'outpost' },
          { name: 'Covalex Hub Gundo', kind: 'station' },
          { name: 'Kudre Ore', kind: 'mining' },
          { name: 'Nuen Waste Management', kind: 'industrial' },
          { name: 'Dunlow Ridge Aid Shelter', kind: 'landing' },
          { name: 'Eager Flats Aid Shelter', kind: 'landing' },
          { name: 'Tamdon Plains Aid Shelter', kind: 'landing' },
          { name: 'Wolf Point Aid Shelter', kind: 'landing' },
          { name: 'Minlo Spire', kind: 'outpost' },
          { name: 'Wailing Rock', kind: 'outpost' },
          { name: 'Hospice', kind: 'outpost' },
          { name: 'The Garden', kind: 'outpost' },
          { name: 'TPF', kind: 'outpost' },
          { name: 'NT-999-XVI', kind: 'outpost' },
          { name: 'Attritus / Lamina PAF & OLP (decommissioned)', kind: 'industrial' },
          { name: "Whistler's Crypt", kind: 'outpost' },
          { name: 'Yadar Valley (unmarked race)', kind: 'racetrack' },
          { name: 'UEES Flyssa wreck', kind: 'outpost' },
          { name: 'Comm Array ST2-47', kind: 'comm_array' },
        ],
      },
      {
        name: 'Yela',
        pois: [
          { name: 'Grim HEX', kind: 'station' },
          { name: 'ArcCorp Mining Area 157', kind: 'mining' },
          { name: 'Deakins Research Outpost', kind: 'outpost' },
          { name: 'Benson Mining Outpost', kind: 'mining' },
          { name: 'Security Post Opal', kind: 'outpost' },
          { name: 'Security Post Wan', kind: 'outpost' },
          { name: 'Half Stack', kind: 'outpost' },
          { name: 'Mainline', kind: 'outpost' },
          { name: "Rolo's Crater", kind: 'outpost' },
          { name: 'Afterlife', kind: 'outpost' },
          { name: "Connor's", kind: 'outpost' },
          { name: 'Utopia', kind: 'outpost' },
          { name: 'NT-999-XX', kind: 'outpost' },
          { name: 'NT-999-XXII', kind: 'outpost' },
          { name: 'Aston Ridge Aid Shelter', kind: 'landing' },
          { name: 'Kosso Basin Aid Shelter', kind: 'landing' },
          { name: 'Nakamura Valley Aid Shelter', kind: 'landing' },
          { name: 'Talarine Divide Aid Shelter', kind: 'landing' },
          { name: "Miner's Lament (zero-G race)", kind: 'racetrack' },
          { name: 'Benny Henge', kind: 'outpost' },
          { name: 'Comm Array ST2-76', kind: 'comm_array' },
        ],
      },
      {
        name: 'Cellin',
        pois: [
          { name: 'Security Post Kareah', kind: 'station' },
          { name: 'Terra Mills HydroFarm', kind: 'outpost' },
          { name: 'Hickes Research Outpost', kind: 'outpost' },
          { name: 'Tram & Myers Mining', kind: 'mining' },
          { name: 'Gallete Family Farms', kind: 'outpost' },
          { name: 'Security Post Criska', kind: 'outpost' },
          { name: 'Security Post Dipur', kind: 'outpost' },
          { name: 'Security Post Lespin', kind: 'outpost' },
          { name: 'The Hollows', kind: 'outpost' },
          { name: 'Consumption', kind: 'outpost' },
          { name: 'Fetch', kind: 'outpost' },
          { name: "Stone's Throw", kind: 'outpost' },
          { name: 'Ashburn Channel Aid Shelter', kind: 'landing' },
          { name: "Flanagan's Ravine Aid Shelter", kind: 'landing' },
          { name: 'Julep Ravine Aid Shelter', kind: 'landing' },
          { name: 'Mogote Aid Shelter', kind: 'landing' },
          { name: 'NT-999-XV', kind: 'outpost' },
          { name: 'PRIVATE PROPERTY (stash site)', kind: 'outpost' },
          { name: 'Comm Array ST2-28', kind: 'comm_array' },
        ],
      },
    ],
  },
  {
    name: 'ArcCorp',
    orbit: 0.58,
    angle: 255,
    color: '#c08050',
    r: 2.8,
    pois: [
      { name: 'Area 18', kind: 'city' },
      { name: 'Baijini Point', kind: 'station' },
      { name: 'Comm Array ST3-90', kind: 'comm_array' },
      { name: 'Area04', kind: 'industrial' },
      { name: 'Area06', kind: 'industrial' },
      { name: 'Area11', kind: 'industrial' },
      { name: 'Area17', kind: 'industrial' },
      { name: 'Area20', kind: 'industrial' },
      { name: 'ArcCorp Tower zone', kind: 'industrial' },
    ],
    moons: [
      {
        name: 'Lyria',
        pois: [
          { name: 'Humboldt Mines', kind: 'mining' },
          { name: 'Loveridge Mineral Reserve', kind: 'mining' },
          { name: 'Shubin Mining Facility SAL-2', kind: 'mining' },
          { name: 'Shubin Mining Facility SAL-5', kind: 'mining' },
          { name: 'Shubin Processing Facility SPAL-3', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPAL-7', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPAL-9', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPAL-12', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPAL-16', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPAL-21', kind: 'industrial' },
          { name: 'Security Depot Lyria-1', kind: 'outpost' },
          { name: 'Comm Array ST3-18', kind: 'comm_array' },
        ],
      },
      {
        name: 'Wala',
        pois: [
          { name: 'Shady Glen Farms', kind: 'outpost' },
          { name: 'ArcCorp Mining Area 045', kind: 'mining' },
          { name: 'ArcCorp Mining Area 048', kind: 'mining' },
          { name: 'ArcCorp Mining Area 056', kind: 'mining' },
          { name: 'ArcCorp Mining Area 061', kind: 'mining' },
          { name: 'ArcCorp Processing Center 115', kind: 'industrial' },
          { name: 'ArcCorp Processing Center 123', kind: 'industrial' },
          { name: 'Lost and Found', kind: 'outpost' },
          { name: 'Good Times Temple', kind: 'outpost' },
          { name: "Samson & Son's Salvage Center", kind: 'industrial' },
          { name: 'Comm Array ST3-35', kind: 'comm_array' },
        ],
      },
    ],
  },
  {
    name: 'MicroTech',
    orbit: 0.78,
    angle: 345,
    color: '#7ab8d4',
    r: 2.4,
    pois: [
      { name: 'New Babbage', kind: 'city' },
      { name: 'Port Tressler', kind: 'station' },
      { name: 'Comm Array ST4-22', kind: 'comm_array' },
      { name: 'Rayari Deltana Research Outpost', kind: 'outpost' },
      { name: 'Rayari Livengood Research Outpost', kind: 'outpost' },
      { name: 'Ghost Hollow', kind: 'outpost' },
      { name: 'Shubin Mining Facility SM0-10', kind: 'mining' },
      { name: 'Shubin Mining Facility SM0-13', kind: 'mining' },
      { name: 'Shubin Mining Facility SM0-18', kind: 'mining' },
      { name: 'Shubin Mining Facility SM0-22', kind: 'mining' },
      { name: 'MT OpCenter LTI-4', kind: 'industrial' },
      { name: 'Covalex Distribution Centre S4DC05', kind: 'industrial' },
      { name: 'Cry-Astro Processing Plant 19-02', kind: 'industrial' },
      { name: 'Cry-Astro Processing Plant 34-12', kind: 'industrial' },
      { name: 'MicroTech Logistics Depot S4LD01', kind: 'industrial' },
      { name: 'MicroTech Logistics Depot S4LD13', kind: 'industrial' },
      { name: 'Sakura Sun Goldenrod Workcenter', kind: 'industrial' },
      { name: 'Greycat Stanton IV Production Complex-A', kind: 'industrial' },
      { name: 'Calhoun Pass Emergency Shelter', kind: 'landing' },
      { name: 'Point Wain Emergency Shelter', kind: 'landing' },
      { name: 'Nuiqsut Emergency Shelter', kind: 'landing' },
      { name: 'Clear View Emergency Shelter', kind: 'landing' },
      { name: 'MT DataCenter 2UB-RB9-5', kind: 'industrial' },
      { name: 'MT DataCenter 4HJ-LVE-A', kind: 'industrial' },
      { name: 'MT DataCenter 5WQ-R2V-C', kind: 'industrial' },
      { name: 'MT DataCenter 8FK-Q2X-K', kind: 'industrial' },
      { name: 'MT DataCenter D79-ECG-R', kind: 'industrial' },
      { name: 'MT DataCenter E2Q-NSG-Y', kind: 'industrial' },
      { name: 'MT DataCenter TMG-XEV-2', kind: 'industrial' },
      { name: 'MT DataCenter QVX-J88-J', kind: 'industrial' },
      { name: 'MT DataCenter L8P-JUC-8 (offline)', kind: 'industrial' },
      { name: 'Outpost 54', kind: 'outpost' },
      { name: 'The Necropolis', kind: 'outpost' },
    ],
    moons: [
      {
        name: 'Calliope',
        pois: [
          { name: 'Shubin Mining Facility SMCa-6', kind: 'mining' },
          { name: 'Shubin Mining Facility SMCa-8', kind: 'mining' },
          { name: 'Shubin Processing Facility SPMC-1', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPMC-3', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPMC-5', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPMC-10', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPMC-11', kind: 'industrial' },
          { name: 'Shubin Processing Facility SPMC-14', kind: 'industrial' },
          { name: 'Rayari Anvik Research Outpost', kind: 'outpost' },
          { name: 'Rayari Kaltag Research Outpost', kind: 'outpost' },
          { name: "Raven's Roost", kind: 'outpost' },
          { name: 'Comm Array ST4-31', kind: 'comm_array' },
        ],
      },
      {
        name: 'Clio',
        pois: [
          { name: 'Rayari Cantwell Research Outpost', kind: 'outpost' },
          { name: 'Rayari McGrath Research Outpost', kind: 'outpost' },
          { name: 'Comm Array ST4-59', kind: 'comm_array' },
        ],
      },
      {
        name: 'Euterpe',
        pois: [
          { name: "Bud's Growery", kind: 'outpost' },
          { name: 'Devlin Scrap & Salvage', kind: 'industrial' },
          { name: 'The Icebreaker', kind: 'racetrack' },
          { name: 'Comm Array ST4-64', kind: 'comm_array' },
        ],
      },
    ],
  },
]

/** System-scale reference (not tied to a single planet body in the tree). */
export const STANTON_SPACE = [
  { name: 'Aaron Halo', kind: 'asteroid_belt', note: 'Asteroid belt between Crusader and ArcCorp (Galactapedia / wiki).' },
  { name: 'HUR-L1 Green Glade Station', kind: 'lagrange', note: 'Hurston L1 R&R rest stop (wiki).' },
  { name: 'HUR-L2 Faithful Dream Station', kind: 'lagrange', note: 'Hurston L2 R&R rest stop (wiki).' },
  { name: 'HUR-L3 Thundering Express Station', kind: 'lagrange', note: 'Hurston L3 R&R rest stop (wiki).' },
  { name: 'HUR-L4 Melodic Fields Station', kind: 'lagrange', note: 'Hurston L4 R&R rest stop (wiki).' },
  { name: 'HUR-L5 High Course Station', kind: 'lagrange', note: 'Hurston L5 R&R rest stop (wiki).' },
  { name: 'CRU-L1 Ambitious Dream Station', kind: 'lagrange', note: 'Crusader L1 R&R rest stop (wiki).' },
  { name: 'CRU-L2 (mining claims)', kind: 'lagrange', note: 'Crusader L2 debris field / claims (wiki).' },
  { name: 'CRU-L3 (mining claims)', kind: 'lagrange', note: 'Crusader L3 debris field / claims (wiki).' },
  { name: 'CRU-L4 Shallow Fields Station', kind: 'lagrange', note: 'Crusader L4 R&R rest stop (wiki).' },
  { name: 'CRU-L5 Beautiful Glen Station', kind: 'lagrange', note: 'Crusader L5 R&R rest stop (wiki).' },
  { name: 'ARC-L1 Wide Forest Station', kind: 'lagrange', note: 'ArcCorp L1 R&R rest stop (wiki).' },
  { name: 'ARC-L2 Lively Pathway Station', kind: 'lagrange', note: 'ArcCorp L2 R&R rest stop (wiki).' },
  { name: 'ARC-L3 Modern Express Station', kind: 'lagrange', note: 'ArcCorp L3 R&R rest stop (wiki).' },
  { name: 'ARC-L4 Faint Glen Station', kind: 'lagrange', note: 'ArcCorp L4 R&R rest stop (wiki).' },
  { name: 'ARC-L5 Yellow Core Station', kind: 'lagrange', note: 'ArcCorp L5 R&R rest stop (wiki).' },
  { name: 'MIC-L1 Shallow Frontier Station', kind: 'lagrange', note: 'microTech L1 R&R rest stop (wiki).' },
  { name: 'MIC-L2 Long Forest Station', kind: 'lagrange', note: 'microTech L2 R&R rest stop (wiki).' },
  { name: 'MIC-L3 Endless Odyssey Station', kind: 'lagrange', note: 'microTech L3 R&R rest stop (wiki).' },
  { name: 'MIC-L4 Red Crossroads Station', kind: 'lagrange', note: 'microTech L4 R&R rest stop (wiki).' },
  { name: 'MIC-L5 Modern Icarus Station', kind: 'lagrange', note: 'microTech L5 R&R rest stop (wiki).' },
]

/** Pyro bodies + major stations (PU + Galactapedia / wiki summaries). */
export const PYRO_BODIES = [
  {
    name: 'Pyro I',
    orbit: 0.12,
    angle: 35,
    color: '#c04010',
    r: 1.9,
    pois: [
      { name: 'Solar flare & radiation hazard zones', kind: 'industrial' },
      { name: 'Distortion storms (lethal irradiation)', kind: 'industrial' },
      { name: 'Northern hemisphere cyclone', kind: 'orbital' },
      { name: 'Surface survey / prospect sites', kind: 'mining' },
    ],
    moons: [],
  },
  {
    name: 'Monox',
    orbit: 0.24,
    angle: 115,
    color: '#a03010',
    r: 2.3,
    pois: [
      { name: 'Abandoned mining complexes', kind: 'industrial' },
      { name: 'Carbon monoxide atmosphere (toxic)', kind: 'industrial' },
      { name: 'Valakkar / deep-worm hazard regions', kind: 'outpost' },
      { name: 'Legacy cadmium & titanium workings', kind: 'mining' },
    ],
    moons: [],
  },
  {
    name: 'Bloom',
    orbit: 0.36,
    angle: 195,
    color: '#cc6820',
    r: 2.4,
    pois: [
      { name: 'Abandoned Pyrotechnic Amalgamated facilities', kind: 'industrial' },
      { name: 'Outlaw & squatter camps', kind: 'outpost' },
      { name: 'Citizens for Prosperity presence', kind: 'outpost' },
      { name: 'Headhunters contest zones', kind: 'outpost' },
      { name: 'XenoThreat contest zones', kind: 'outpost' },
      { name: 'Brine seas & temperate biomes', kind: 'mining' },
      { name: 'Cave Kopion habitats', kind: 'outpost' },
    ],
    moons: [],
  },
  {
    name: 'Pyro IV',
    orbit: 0.48,
    angle: 275,
    color: '#884030',
    r: 2.0,
    pois: [
      { name: 'Captured orbit of Pyro V', kind: 'orbital' },
      { name: 'Warped collision geology', kind: 'mining' },
      { name: 'Reformed atmosphere — surface expeditions', kind: 'outpost' },
    ],
    moons: [],
  },
  {
    name: 'Pyro V',
    orbit: 0.62,
    angle: 355,
    color: '#5a9020',
    r: 3.1,
    pois: [
      { name: 'Hydrogen skimming (upper atmosphere)', kind: 'industrial' },
      { name: 'Low-yield refuel lanes', kind: 'industrial' },
    ],
    moons: [
      { name: 'Ignis', pois: [{ name: 'Deep canyons & dry riverbeds', kind: 'outpost' }, { name: 'SO₂ atmosphere — suit O₂ scrape', kind: 'industrial' }] },
      { name: 'Vatra', pois: [{ name: 'N₂–CH₄ haze & hydrocarbon flora', kind: 'outpost' }] },
      { name: 'Adir', pois: [{ name: 'Craters & jagged highlands', kind: 'mining' }] },
      { name: 'Fairo', pois: [{ name: 'Seismic brackish seas', kind: 'mining' }, { name: 'Subsurface ecology sites', kind: 'outpost' }] },
      { name: 'Fuego', pois: [{ name: 'Iron-sulfide badlands', kind: 'mining' }, { name: 'Headhunters stash lore regions', kind: 'outpost' }] },
      { name: 'Vuur', pois: [{ name: 'Crystalline carbon flora', kind: 'mining' }, { name: 'Warmer carbon-rich basins', kind: 'outpost' }] },
    ],
  },
  {
    name: 'Terminus',
    orbit: 0.78,
    angle: 70,
    color: '#708090',
    r: 2.2,
    pois: [
      { name: 'Ruin Station (orbital)', kind: 'station' },
      { name: 'Neutrality (bar inside Ruin Station)', kind: 'outpost' },
      { name: 'Corner Four (labs / drug factories)', kind: 'industrial' },
      { name: 'XenoThreat, Overlords, Fire Rats, Darkside Rovers (contested)', kind: 'outpost' },
      { name: 'Methane ice surface expeditions', kind: 'mining' },
    ],
    moons: [],
  },
]

export const PYRO_SPACE = [
  { name: 'Stanton Gateway', kind: 'gate', note: 'Jump station toward Stanton (Galactapedia / in-game).' },
  { name: 'Nyx Gateway', kind: 'gate', note: 'Jump station toward Nyx (Galactapedia / in-game).' },
  { name: 'Akiro Cluster', kind: 'asteroid_belt', note: 'Charred asteroids near Pyro I L3; rare materials (wiki / Starmap).' },
  { name: 'Checkmate Station (Monox L4)', kind: 'lagrange', note: "Rough & Ready HQ; Fool's Run exterior race (wiki)." },
  { name: 'Orbituary', kind: 'station', note: 'Above Bloom — Rough & Ready marketplace, clinic, habs (wiki).' },
  { name: 'Pyro V Lagrange platforms', kind: 'lagrange', note: 'Former Pyrotechnic Amalgamated stations at L-points (Galactapedia).' },
  { name: 'Terminus Lagrange (PA derelicts)', kind: 'lagrange', note: 'Former Pyrotechnic stations at Terminus L-points (wiki).' },
  { name: 'Pyro I Lagrange (PA derelicts)', kind: 'lagrange', note: 'Abandoned company stations at Pyro I L-points (wiki).' },
  {
    name: 'Minor asteroid clusters',
    kind: 'asteroid_belt',
    note: 'Named clusters e.g. BGR-560, CAJ-445, EMM-567, FSN-704, GRP-839, JWY-925, HJS-232, KKE-717, LHB-976, MNK-833, NDB-102, PQE-291, RSC-340, SGL-693, SZA-178, TYS-908, VUP-613, WDH-387, YKA-011 (wiki Pyro system).',
  },
  { name: 'Rough & Ready stations', kind: 'station', note: 'Faction hubs including Checkmate & Orbituary (wiki).' },
  { name: 'Citizens for Prosperity stations', kind: 'station', note: 'CfP-controlled sites in Pyro (wiki system summary).' },
]

/** Nyx bodies + Levski (Alpha 4.4+); belts & gates in NYX_SPACE. */
export const NYX_BODIES = [
  {
    name: 'Nyx I',
    orbit: 0.2,
    angle: 40,
    color: '#7a6a58',
    r: 2.2,
    pois: [
      { name: 'Gold Horizon legacy strip mines', kind: 'mining' },
      { name: 'Coreless depleted husk — surface ruins', kind: 'outpost' },
    ],
    moons: [],
  },
  {
    name: 'Nyx II',
    orbit: 0.38,
    angle: 160,
    color: '#8a5038',
    r: 2.35,
    pois: [
      { name: 'High-pressure acid & CO₂ clouds', kind: 'industrial' },
      { name: 'No major landing zones', kind: 'orbital' },
    ],
    moons: [],
  },
  {
    name: 'Delamar',
    orbit: 0.56,
    angle: 280,
    color: '#6b7580',
    r: 2.15,
    pois: [
      { name: 'Levski (free port)', kind: 'city' },
      { name: 'Cargo Deck', kind: 'station' },
      { name: 'Mercy Hospital', kind: 'station' },
      { name: "Teach's Ship Shop", kind: 'station' },
      { name: 'Grand Barter Bazaar', kind: 'outpost' },
      { name: 'Conscientious Objects (weapons)', kind: 'outpost' },
      { name: "Cordry's (armor)", kind: 'outpost' },
      { name: 'Café Musain', kind: 'outpost' },
      { name: 'Refinery deck', kind: 'industrial' },
      { name: 'Municipal Services', kind: 'industrial' },
      { name: 'Anthony Tanaka memorial', kind: 'outpost' },
      { name: 'Exterior landing towers & pads', kind: 'landing' },
    ],
    moons: [],
  },
  {
    name: 'Nyx III',
    orbit: 0.76,
    angle: 95,
    color: '#4a6a8a',
    r: 2.5,
    pois: [
      { name: 'Ice giant — no breathable surface', kind: 'orbital' },
      { name: 'Outer system refuel / survey lanes', kind: 'industrial' },
    ],
    moons: [],
  },
]

export const NYX_SPACE = [
  { name: 'Glaciem Ring (Nyx belt alpha)', kind: 'asteroid_belt', note: 'Dense inner belt; Delamar embedded here (Galactapedia).' },
  { name: 'Keeger Belt (Nyx belt beta)', kind: 'asteroid_belt', note: 'Outermost belt; suspected outlaw strongholds (Galactapedia).' },
  { name: 'Moraine settlements', kind: 'outpost', note: 'Smuggler faction sites scattered through the Glaciem Ring (wiki).' },
  {
    name: "People's service stations",
    kind: 'station',
    note: "Keeger Belt — former QV Planet Services hubs, now People's Alliance (Alpha 4.7+; wiki).",
  },
  { name: 'Pyro Gateway (Nyx side)', kind: 'gate', note: 'Jump interface toward Pyro (wiki jump table).' },
  { name: 'Stanton jump (Nyx)', kind: 'gate', note: 'Large bidirectional JP toward Stanton (wiki Nyx system).' },
  { name: 'Castra / Bremen / Odin / Tohil / Virgil jumps', kind: 'gate', note: 'Additional large/medium links on RSI Starmap (not all PU).' },
]
